### ISSUE TITLE
[建议]建议支持apprise推送

### ISSUE THREAD

**Issue by hhhllll888** [easychen/pushdeer#101]
<https://github.com/caronc/apprise>

**Comment by easychen** [comment]
不太明白什么意思，如果需要使用 apprise，直接用它的客户端不就好了吗？

**Comment by easychen** [comment]
额，我重新看了下apprise，你是不是想说，让 apprise 支持 pushdeer 🤣

**Comment by hhhllll888** [comment]
> 额，我重新看了下apprise，你是不是想说，让 apprise 支持 pushdeer 🤣

对对，抱歉我说的不清楚

**Comment by easychen** [comment]
我看已经 apprise 有 @xuzheliang135 贡献的 serverchan 插件，或许可以等用python的同学改改。 https://github.com/caronc/apprise/blob/master/apprise/plugins/NotifyServerChan.py

**Comment by StimeKe** [comment]
我已经为Apprise贡献了PushDeer的插件，可以关掉这个Issues了。
https://github.com/caronc/apprise/pull/904
