### ISSUE TITLE
[Bug]：推送base64格式的图片，返回414错误，uri too long

### ISSUE THREAD

**Issue by LIN-HongTao** [easychen/pushdeer#104]
**描述你遇到的Bug**

我用matplotlib制作折线图，转换成base64，长度有8w+，发送时报错414，

**重现**

重现步骤:
data = 'data:image/png;base64,xxxxx.....'  # xxx长度是8w+
pushdeer = PushDeer(pushkey="xxx")
pushdeer.send_image(data)

我把get请求改成post请求依旧是414错误

**期望的结果**
正确推送

**截图**
![image](https://user-images.githubusercontent.com/22323046/163718769-e8d7f4b9-f9ca-4ed8-9701-068a3492cd7a.png)

**Comment by easychen** [comment]
虽然这个错误表面是url超长，但后边还有整个请求大小限制。以及pushdeer对内容的长度的限制，大概在2万字，因此基本上支持不了base64图片。

图片还是需要传到图床后，再用url进行推送。
