### ISSUE TITLE
要不出个群晖nas，pushdeer的简单说明？

### ISSUE THREAD

**Issue by horseytr** [easychen/pushdeer#108]
要不出个群晖nas，pushdeer的简单说明？

**Comment by easychen** [comment]
没有群晖所以无法测试…… 等有的同学贡献吧。不过按理说只要docker可以应该都能用吧。

**Comment by qqsir-dev** [comment]
docker 下能运行，没问题

**Comment by woliu-20** [comment]
是想问群辉上docker自架服务，还是群辉通知通过pushdeer推送。

**Comment by easychen** [comment]
> 是想问群辉上docker自架服务，还是群辉通知通过pushdeer推送。

自架版是完全独立的，不走pushdeer在线版，直接通过苹果和小米平台推送。

**Comment by Gavin-J** [comment]
> 没有群晖所以无法测试…… 等有的同学贡献吧。不过按理说只要docker可以应该都能用吧。
五一这几天我出一个

**Comment by horseytr** [comment]
> docker

是指群晖nas 外网ip变化，断电或则错误等一些状态变化，发送给pushdeer

**Comment by woliu-20** [comment]
> 

在群辉控制面板 -> 通知设置 -> 规则 可以设定需要推送的事件。
在群辉控制面板 -> 通知设置 -> 推送服务 -> 应用程序webhook -> 管理webhook

新增 -> 自定义

提供商名称：（随意填写）
主题：（发生事件推送给你的内容，自定义内容可参照[这里](https://kb.synology.cn/zh-cn/DSM/help/DSM/AdminCenter/system_notification_filter?version=7)）
webhook url：`https://api2.pushdeer.com`/message/push?pushkey=`key`&text=hello world（自建服务请替换`https://api2.pushdeer.com`为自建服务。`key`替换为app内创建的key）

参数类型
pushkey 其他参数
text 消息内容

似乎6.x没webhook。

文档[这里](https://kb.synology.cn/zh-cn/DSM/help/DSM/AdminCenter/system_notification_pushservice?version=7)

**Comment by woliu-20** [comment]
> > 是想问群辉上docker自架服务，还是群辉通知通过pushdeer推送。
> 
> 自架版是完全独立的，不走pushdeer在线版，直接通过苹果和小米平台推送。

嗯。。是想问他想问啥。。我也试了下，我这边群辉docker自架没问题:smile:

**Comment by horseytr** [comment]
> > 
> 
> 在群辉控制面板 -> 通知设置 -> 规则 可以设定需要推送的事件。 在群辉控制面板 -> 通知设置 -> 推送服务 -> 应用程序webhook -> 管理webhook
> 
> 新增 -> 自定义
> 
> 提供商名称：（随意填写） 主题：（发生事件推送给你的内容，自定义内容可参照[这里](https://kb.synology.cn/zh-cn/DSM/help/DSM/AdminCenter/system_notification_filter?version=7)） webhook url：`https://api2.pushdeer.com`/message/push?pushkey=`key`&text=hello world（自建服务请替换`https://api2.pushdeer.com`为自建服务。`key`替换为app内创建的key）
> 
> 参数类型 pushkey 其他参数 text 消息内容
> 
> 似乎6.x没webhook。
> 
> 文档[这里](https://kb.synology.cn/zh-cn/DSM/help/DSM/AdminCenter/system_notification_pushservice?version=7)

好人一生平安
