### ISSUE TITLE
iPhone 通知不能显示完整消息内容（desp的内容）

### ISSUE THREAD

**Issue by tanmx** [easychen/pushdeer#110]
现在收到通知只 显示标题，正文部分显式为 from pushdeer ，需要点开消息才能看到完整内容，是项目调整了么？
新消息

![image](https://user-images.githubusercontent.com/3370587/165419735-b3adaf12-0fb2-4d8c-b532-66b87d87e788.png)
点开消息才看到完整内容
![image](https://user-images.githubusercontent.com/3370587/165419739-e5e728b7-19bf-4c4c-b556-d96a076ceaff.png)

**Comment by easychen** [comment]
![image](https://user-images.githubusercontent.com/1294760/165430669-a1254ed3-13de-4e3d-b780-ee0cd6545f7e.png)

iOS通知区域一直都没显示desp的内容啊，只是加了subtitle而已。这么设计的主要原因是这个区域不支持 markdown，所以推荐纯文本放到 text，markdown 放到 desp。

**Comment by tanmx** [comment]
@easychen 感谢释疑
