### ISSUE TITLE
有自架版的群或者详细一些的文档吗？

### ISSUE THREAD

**Issue by LIN-HongTao** [easychen/pushdeer#111]
感觉对自架版的功能还不太熟悉
比如/device/list返回的是啥呢？
我已经注册了自己的ios设备，也可以收到消息了，但是/device/list返回的还是空列表
{
    "code": 0,
    "content": {
        "devices": []
    }
}

**Comment by easychen** [comment]
https://github.com/easychen/pushdeer/blob/main/doc/api/PushDeerOS.md#post-devicelist

**Comment by LIN-HongTao** [comment]
我就是按这个步骤来的，先登录然后调设备列表，但是是空的
![image](https://user-images.githubusercontent.com/22323046/165671081-8483f624-ae35-4559-9d9f-b73b42d35df3.png)
![image](https://user-images.githubusercontent.com/22323046/165671093-bf0ce9fc-8dce-419a-a971-11d22d608a80.png)

**Comment by easychen** [comment]
fakelogin 走的是一个独立测试账号，和你客户端的那个账号不是一个。如果你要通过接口查客户端，需要得到对应的token，比如通过抓包获得。
