### ISSUE TITLE
esp8266 编译始终不通过

### ISSUE THREAD

**Issue by Hsnico** [easychen/pushdeer#112]
```
D:\pushdeer\iot\deeresp\deeresp.ino: In lambda function:

deeresp:42:20: error: 'PIN_D8' was not declared in this scope; did you mean 'PIN_A0'?

   42 |   #define BEEP_PIN PIN_D8

      |                    ^~~~~~

D:\pushdeer\iot\deeresp\deeresp.ino:95:42: note: in expansion of macro 'BEEP_PIN'

   95 |     if(payload.indexOf("♪") >= 0) tone(BEEP_PIN, 1000, 100);

      |                                        ^~~~~~~~
```

尝试过卸载 Arduino，并手动清空相关库，重新安装后依旧会出现相同的报错

![20220429_005305](https://user-images.githubusercontent.com/59398077/165804364-0832d157-1abb-4969-a60b-b400d4250c28.jpg)

**Comment by easychen** [comment]
PIN_D8 是在TFT_eSPI中定义的，没有安装 TFT_eSPI 库吗？

解决办法有两个，一个是用过 IDE 把 TFT_eSPI 库装上，另一个是 把 PIN_D8 换成 15 

![image](https://user-images.githubusercontent.com/1294760/165875204-2be87c89-9037-40ce-a3d4-f2c3ea22363d.png)

**Comment by Hsnico** [comment]
看了下是把 TFT_eSPI.h 中的 #include <User_Setup_Select.h> 修改成了  ST7789 屏幕的 User_Setup.h 导致的，修改回来可以正常通过编译，在 User_Setup_Select.h 中是有关于 PIN_D8 的定义的

**Comment by Hsnico** [comment]
> PIN_D8 是在TFT_eSPI中定义的，没有安装TFT_eSPI库吗？
> 
> 解决办法有两个，一个是用过 IDE 把 TFT_eSPI 库装上，另一个是把 PIN_D8 换成 15
> 
> ![图片](https://user-images.githubusercontent.com/1294760/165875204-2be87c89-9037-40ce-a3d4-f2c3ea22363d.png)

看了下是把 TFT_eSPI.h 中的 #include <User_Setup_Select.h> 修改成了 ST7789 屏幕的 User_Setup.h 导致的，修改回来可以正常通过编译，在 User_Setup_Select.h 中是有关于 PIN_D8 的定义的
