### ISSUE TITLE
怎么感觉没有bark简介好看-附图

### ISSUE THREAD

**Issue by lalasou** [easychen/pushdeer#115]
![image](https://user-images.githubusercontent.com/7440313/168275198-b4cd8f0b-c476-458c-b1c8-67b1f9951bc1.jpeg)

![image](https://user-images.githubusercontent.com/7440313/168275223-3825a339-6265-4fe2-82c7-8399ce788b6b.jpeg)

![image](https://user-images.githubusercontent.com/7440313/168275257-cc4c6ec6-d0d0-471e-aeb2-641fcd10f385.jpeg)

**Comment by easychen** [comment]
PushDeer 的 desp 支持 markdown，所以不能直接在通知栏显示。
