### ISSUE TITLE
如何在安卓app中删除无用的设备？

### ISSUE THREAD

**Issue by cc1990** [easychen/pushdeer#116]
在手机上安装、卸载、安装，重复多次之后，会生成一些设备信息，请问这个该如何删除无用的设备信息？
还有一些测试数据，该如何删除？

![175c65839e4a05043becf96f5bc7e0a](https://user-images.githubusercontent.com/11643313/168408645-fc0ea3eb-7101-4d49-8061-ac8a1a7d957d.jpg)

![6da2891a682b1bfcf5633fde71ae7a0](https://user-images.githubusercontent.com/11643313/168408649-0732cbca-d2ef-46a3-9c1c-bc6fac4b4a1e.jpg)

**Comment by easychen** [comment]
横向滑动
