### ISSUE TITLE
能否详细说一下不用Docker-compose的操作步骤

### ISSUE THREAD

**Issue by huhu415** [easychen/pushdeer#118]
我用默认Docker-compose成功搭建了，但我看文档，我发现有个文档里写Docker-compose只适合开发者不适合放置到线上，但这个文档说放证书和改docker/web/vhost.conf文件，我没找到这个conf文件啊，所以想请作者细说一下应该怎么变https，和是不是变成https就安全了哪？

**Comment by easychen** [comment]
> 我用默认Docker-compose成功搭建了，但我看文档，我发现有个文档里写Docker-compose只适合开发者不适合放置到线上，但这个文档说放证书和改docker/web/vhost.conf文件，我没找到这个conf文件啊，所以想请作者细说一下应该怎么变https，和是不是变成https就安全了哪？

https://github.com/easychen/pushdeer/blob/main/docker/web/vhost.conf
