### ISSUE TITLE
[Bug]MAC版客户端 无法登陆了

### ISSUE THREAD

**Issue by City-Zero** [easychen/pushdeer#133]
<img width="541" alt="image" src="https://user-images.githubusercontent.com/19517295/177902529-00b7c0d6-58ba-4b0a-a1b7-caf0a757ac9f.png">

**Comment by nov12** [comment]
应该是服务器崩了吧，我是早晨8点多好像就发现推送收不到了。

**Comment by easychen** [comment]
服务器磁盘满了，已经修复了。
