### ISSUE TITLE
按照文档部署后，注册500错误，前台启动docker-compose日志如下

### ISSUE THREAD

**Issue by hczs** [easychen/pushdeer#144]
好像是无法连接数据库
pushdeer-app-1      | Setting php-fpm user to application
pushdeer-app-1      | -> Executing /opt/docker/bin/service.d/cron.d//10-init.sh
pushdeer-app-1      | [2022-08-25T10:24:41.656642] WARNING: With use-dns(no), dns-cache() will be forced to 'no' too!;
pushdeer-app-1      | [SYSLOG] syslog-ng[83]: syslog-ng starting up; version='3.19.1'
pushdeer-app-1      | [Thu Aug 25 10:24:41.718684 2022] [mpm_event:notice] [pid 87:tid 139997942875264] AH00489: Apache/2.4.38 (Debian) OpenSSL/1.1.1n configured -- resuming normal operations
pushdeer-app-1      | [Thu Aug 25 10:24:41.718838 2022] [core:notice] [pid 87:tid 139997942875264] AH00094: Command line: 'apache2 -D FOREGROUND -D APACHE_LOCK_DIR'
pushdeer-app-1      | [SYSLOG] cron[88]: (CRON) INFO (pidfile fd = 3)
pushdeer-app-1      | [SYSLOG] cron[88]: (*system*larave-cron) ERROR (Missing newline before EOF, this crontab file will be ignored)
pushdeer-app-1      | [SYSLOG] cron[88]: (CRON) INFO (Skipping @reboot jobs -- not system startup)
pushdeer-app-1      | [25-Aug-2022 10:24:41] NOTICE: fpm is running, pid 86
pushdeer-app-1      | [25-Aug-2022 10:24:41] NOTICE: ready to handle connections
pushdeer-app-1      | 2022-08-25 10:24:42,805 INFO success: syslogd entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
pushdeer-app-1      | 2022-08-25 10:24:42,805 INFO success: push-ios entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
pushdeer-app-1      | 2022-08-25 10:24:42,805 INFO success: push-clip entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
pushdeer-mariadb-1  | 2022-08-25 10:25:07 5 [Warning] Access denied for user 'root'@'localhost' (using password: YES)

**Comment by hczs** [comment]
尝试打开服务器3306端口但是无效，服务器目前只开启了8800端口，是否还需要开启其他端口？
pushdeer-mariadb-1  | 2022-08-25 10:25:07 5 [Warning] Access denied for user 'root'@'localhost' (using password: YES)
pushdeer-mariadb-1  | 2022-08-25 10:25:37 6 [Warning] Access denied for user 'root'@'localhost' (using password: YES)
pushdeer-mariadb-1  | 2022-08-25 10:26:07 7 [Warning] Access denied for user 'root'@'localhost' (using password: YES)
pushdeer-mariadb-1  | 2022-08-25 10:26:37 8 [Warning] Access denied for user 'root'@'localhost' (using password: YES)
pushdeer-mariadb-1  | 2022-08-25 10:27:07 9 [Warning] Access denied for user 'root'@'localhost' (using password: YES)
pushdeer-mariadb-1  | 2022-08-25 10:27:37 10 [Warning] Access denied for user 'root'@'localhost' (using password: YES)
pushdeer-mariadb-1  | 2022-08-25 10:28:07 11 [Warning] Access denied for user 'root'@'localhost' (using password: YES)
pushdeer-mariadb-1  | 2022-08-25 10:28:38 12 [Warning] Access denied for user 'root'@'localhost' (using password: YES)
pushdeer-mariadb-1  | 2022-08-25 10:29:08 13 [Warning] Access denied for user 'root'@'localhost' (using password: YES)

**Comment by w9029** [comment]
遇到了相同的问题，请问解决了吗？
