### ISSUE TITLE
关于二次开发/签名问题

### ISSUE THREAD

**Issue by PeanutMelonSeedBigAlmond** [easychen/pushdeer#147]
如题，因为现在 Android 版本有一些小问题，想试着修复一下，但是如果使用我自己的签名的话，会导致微信登录无法验证，所以，是否能提供一下签名文件？

可以的话，我的邮箱地址在 GitHub 个人资料页面。

再次感谢

**Comment by easychen** [comment]
签名文件不方便对外提供，可能会导致出现官方包被植入广告和恶意程序用户无法感知。

如果是调试用，可以改用 fakeLogin接口，或者昨天新添加的 Simple Token接口 （ https://github.com/easychen/pushdeer#simple-token ） 登入，这样无需使用微信登入就可以调试。完成后可以PR回来，我们再打包发布。

或者您修改包名后，自己到腾讯申请一个签名。
