### ISSUE TITLE
[Bug]鸿蒙2.0 进入后台后无法收到通知

### ISSUE THREAD

**Issue by TaSnow** [easychen/pushdeer#151]
机型：华为mate30pro
系统：鸿蒙2.0
问题：
软件进入后台后无法收到推送消息（相关权限已全部开启）
![1111](https://user-images.githubusercontent.com/6203735/191698212-010c05fc-1430-494f-aaf1-e6127d30a7ea.png)

**Comment by PikuZheng** [comment]
有个app叫手机管家。里面点应用启动管理，找到这个appp，关闭自动管理，会跳出三个开关，都允许。试试

**Comment by PikuZheng** [comment]
还不行就设置-应用-电池优化 改成不允许

**Comment by TaSnow** [comment]
> 有个app叫手机管家。里面点应用启动管理，找到这个appp，关闭自动管理，会跳出三个开关，都允许。试试

试了下还是收不到消息推送

**Comment by TaSnow** [comment]
> 还不行就设置-应用-电池优化 改成不允许
感谢回复，不过还是没收到消息推送

**Comment by easychen** [comment]
MiPush的接口被关了，参考这条  https://github.com/easychen/pushdeer/issues/150
