### ISSUE TITLE
iPhone上是否会支持通知栏展示subtitle?

### ISSUE THREAD

**Issue by leafney** [easychen/pushdeer#157]
首先，非常感谢开发者，相比于其他类似工具，pushdeer用起来很舒服

翻看了相关的issues，也自己多次测试后发现，目前在iPhone上只能显示一行text标题内容，desc部分不会在通知栏显示。

在锁屏界面下查看通知，对于仅显示一行标题内容似乎太过于简单，要想查看更多信息必须点开通知后才能看到完整信息。个人考虑如果是支持 title + subtitle 的情况，直接在锁屏状态下一目了然就能看到更多信息，对于更详细的 desc 则可以在点开通知后查看，似乎体验会更好一些。当然，这里的 title 和 subtitle 均指纯文本类型。

例如我的通知内容如下，我期望在通知栏能够直接看到 title 和 subtitle 两项：
- title : 今日天气
- subtitle: 北京天气晴，东风一级
- desc: 其他的信息

另外，看项目源码中之前是有支持subtitle参数的：https://github.com/easychen/pushdeer/blob/d7a0c95382d672fddab64b17c5895afe8faae964/api/app/Http/Helpers.php#L120
那应该是能够自定义，不知是考虑什么原因没有支持？

**Comment by easychen** [comment]
desp可能包含markdown，因此不适合显示到通知栏。如果你确实需要，而且使用自架版，可以手工把那行代码改改，把 subtitle 指定成 desp 就好了。
