### ISSUE TITLE
Composer 依赖安装报错

### ISSUE THREAD

**Issue by 100gle** [easychen/pushdeer#158]
# 问题描述

基于自建脚本通过 `docker-compose` 启动后在安装相关 PHP 依赖时出现下载失败的情况，不论是否开着代理都无法解决：

![截屏2022-11-01 21 55 10](https://user-images.githubusercontent.com/36526527/199252185-a0967676-d0a1-4742-8807-f0d79e0c3633.png)

- 操作系统：macOS 12.3.1 
- Docker Compose 版本：v2.10.2
- Docker 版本：20.10.17

**Comment by PikuZheng** [comment]
考虑dns问题，用safari可以正常打开 https://codeload.github.com 吗

**Comment by 100gle** [comment]
> 考虑dns问题，用safari可以正常打开 https://codeload.github.com 吗

挂代理的情况下可以打开

**Comment by 100gle** [comment]
看起来确实是 DNS 的问题，通过 SwithHost 调整 DNS 然后重新配置了一下代理，已解决。
