### ISSUE TITLE
[Bug]发送消息内容过长时，发生错误

### ISSUE THREAD

**Issue by Pleasecallmeboss** [easychen/pushdeer#161]
**描述你遇到的Bug**

使用官方在线版，内容少时正常
当发送的内容大于get请求规定的长度后，发送会失败。
我认为是get请求限制了能够发送的消息长度，可以开发使用post请求的推送机制吗，post请求没有内容长度的限制。

具体报错信息如下
![image](https://user-images.githubusercontent.com/50833519/204499963-2150c1d6-35ce-4974-bc76-4129a5f8697f.png)

**重现**

重现步骤:

1. 发送很长的内容即可，我报错时发送了大约3000的汉字

推送使用github action，
python版本3.10

接收使用的是ios 16.0

**Comment by easychen** [comment]
本来就支持POST，文档里边PHP函数就用的POST。

https://github.com/easychen/pushdeer#%E5%8F%91%E9%80%81%E5%AE%9E%E4%BE%8B
