### ISSUE TITLE
PushDeer 推送 key 是什么?

### ISSUE THREAD

**Issue by xqin** [easychen/pushdeer#17]
![image](https://user-images.githubusercontent.com/1265888/150122847-b2b12682-4b89-4f3c-99c9-318df0c7cd60.png)

仓库中并未找到推送的key文件,  请问自建服务器如何能将消息推送至 PushDeer 的轻应用上?

Bark 的开发者 允许用户自建 Server, 推送key是公开的.  (https://github.com/Finb/bark-server/tree/master/deploy)

**Comment by easychen** [comment]
那个不是key，是推送证书。PushDeer目前仅提供源码，需自行注册apple开发者并生成证书。

**Comment by xqin** [comment]
所以 PushDeer 并不像 Bark 那样 允许用户基于 PushDeer App 自建 推送的后端, 我这么理解对吧?

**Comment by easychen** [comment]
> 所以 PushDeer 并不像 Bark 那样 允许用户基于 PushDeer App 自建 推送的后端, 我这么理解对吧?

首先 PushDeer 的 APP 和后端都是开源的，你完全可以自建服务器端+自行编译客户端上架。

其次，你要的不是什么自架，而是别人买开发者账号生成证书给你用。我们认为这种做法存在安全和内容风险，需在团队讨论后，以更可控的方式来实现。

**Comment by ptsa** [comment]
其实官方app 然后 可以自定义服务器这样也挺好的 bitwarden 就是这样的

**Comment by YuanZhou314** [comment]
所以我的自架版推送失效是证书的原因吗，应用里能收到消息，但系统收不到推送。去年就搭好了，最近发现用不了了，目前还在用官方版代替

**Comment by easychen** [comment]
![image](https://user-images.githubusercontent.com/1294760/229346832-fc90df20-17fe-4014-a35b-166e2825e1ff.png)
