### ISSUE TITLE
[非Bug] 私有的endpoint没有安全认证，任何人都可以连接注册

### ISSUE THREAD

**Issue by midaug** [easychen/pushdeer#176]
问题一：
我使用docker搭建的自架服务器端已经可以正常推送到我的iphone，但是发现不管是服务的还是客户端并没有对我的服务器有任何安全措施   

只要别人能拿到我的endpoint那么任何人都可以注册到我的服务器进行推送，但其实我只想我授权的设备才能注册    

是否可以在服务的和客户端之间的连接增加安全校验，比如token，客户端需要输入endpoint和token才能注册

问题二：
在上面安全的保障下，除了手动删数据库是否可以增加快速移除非法注册设备的方式

@easychen

**Comment by easychen** [comment]
自架版并不是私有版，主要场景是自架提供公共服务。正因此，官方目前没有类似功能的开发计划，欢迎PR。

**Comment by midaug** [comment]
> 

需要自架本质上是为了私有，期望推送的消息只经过自己的服务器。 如果在自己的公共服务器上架设又没有任何防护极容易被攻击，例如里面的wechatLogin调用了微信的public api，如果这个接口被攻击下游微信的接口必然受影响，很可能微信会将公共服务器拉黑

另外如果被攻击也没有有效的手段拦截，别人的ip可能是动态的，就只能关闭pushdeer服务

加一重防护即可以满足私有需求又可以一定程度保障安全

**Comment by easychen** [comment]
我同意你的看法，除了限制用户注册，甚至还可加上付费接口进行收费。只是我们目前计划表上没有这个功能。这是一个由社区驱动的开源项目，如果你发现无法满足你的需求，完全可以自己或者雇人二次开发。

即使作为普通用户，你也可以在docker外层去做防护，比如ip限制，或者直接把注册接口的URL禁止掉。

**Comment by midaug** [comment]
目前用这种方式实现，没次新设备注册需要手动注释location  /push/login/    后面计划可以考虑一下：比如 开启/关闭 login功能，或者生成临时授权注册码

`
 location  /push/login/   {
     deny all;
 }
location /push/ {
    proxy_set_header X-Forwarded-For    $remote_addr;
    proxy_set_header X-Real-IP          $remote_addr;
    proxy_pass    http://127.0.0.1:8800/;
}
`
