### ISSUE TITLE
问个不知道合不合适的问题

### ISSUE THREAD

**Issue by AlanDinkle** [easychen/pushdeer#18]
这个轻应用就是在不同设备间，使用浏览器输入一段代码以发送消息的吗？
##那和普通的在APP内发送消息有什么区别呀？
##而且如果要实现群发功能怎么办呢？

**Comment by easychen** [comment]
> 这个轻应用就是在不同设备间，使用浏览器输入一段代码以发送消息的吗？ ##那和普通的在APP内发送消息有什么区别呀？ ##而且如果要实现群发功能怎么办呢？

1. 可以通过脚本调用。
2. 拿到要发送人的key，多次调用。
