### ISSUE TITLE
[Bug]自架版App登录报错

### ISSUE THREAD

**Issue by kiddyyang** [easychen/pushdeer#185]
**描述你遇到的Bug**

自架版App之前可正常使用，最近突然接收不到通知，然后发现App无法正常登录了。报错见截图

以下内容不是必填，但越详细越能帮助我们解决问题。

**重现**

重现步骤:

**期望的结果**

**截图**
![a5c5256d3396a7f00ea1ed001e23ab1](https://github.com/easychen/pushdeer/assets/11471064/81dae4ac-b1d7-4613-b792-5e779d61100f)

**自架服务器端请填写以下信息**

按 [调试文档](/doc/调试文档.md) 进行调试的结果：

**API服务启动输出截图**

自架版服务启动正常
![image](https://github.com/easychen/pushdeer/assets/11471064/f218796d-2613-41c0-ba05-53350ec62f18)

**联通性测试截图**

**命令行推送返回截图**

**客户端请填写以下信息**

**环境和版本**
 - 系统: [如 Mac、iOS、Android、ESP]
 - 版本： [如自架版1.2，官方版1.2]
 - 模块：[如客户端、服务器端、Docker-compose、Docker独立镜像] 
 - 版本号 [如 22]

**手机或电脑的的详细信息**

 **收不到消息请填写**
 - 是否注册设备: [是/否]
 - 是否注册当前设备: [是/否]（ 设备页面有设备名称后显示「当前设备」 ）
 - 是否开通通知权限: [是/否]
 - 是否开重装过应用: [是/否]
 - APP和轻APP（Clip）是否分别都注册过设备: [是/否]
 
 - 注册设备页面截图
 - 应用通知设置页面截图
 
> 大部分用户在尝试删除重装应用后，可以修复问题，您也可以试试 
 
**其他说明**

**Comment by PikuZheng** [comment]
如果一直好用然后突然不好了，有没有可能是自架的服务器https证书到期了
