### ISSUE TITLE
[Bug] 部署失败 Segmentation fault (core dumped)

### ISSUE THREAD

**Issue by xfrqh** [easychen/pushdeer#187]
**描述你遇到的Bug**

按wiki在自己服务器用docker部署，初次启动时报错`Segmentation fault (core dumped)`

**重现**

重现步骤:

    root@server1:~# git clone https://gitee.com/easychen/pushdeer.git
    Cloning into 'pushdeer'...
    remote: Enumerating objects: 3449, done.
    remote: Counting objects: 100% (95/95), done.
    remote: Compressing objects: 100% (73/73), done.
    remote: Total 3449 (delta 31), reused 58 (delta 18), pack-reused 3354
    Receiving objects: 100% (3449/3449), 148.53 MiB | 5.48 MiB/s, done.
    Resolving deltas: 100% (1459/1459), done.
    Updating files: 100% (1106/1106), done.
    root@server1:~# cd pushdeer
    root@server1:~/pushdeer# sudo docker-compose -f docker-compose.self-hosted.yml up --build -d 
    Segmentation fault (core dumped)

**期望的结果**
pushdeer 正常启动

**自架服务器端请填写以下信息**

**其他说明**

**Comment by PikuZheng** [comment]
看起来是架构错误，什么CPU？
