### ISSUE TITLE
可否支持更多客户端接收推送消息？

### ISSUE THREAD

**Issue by yoogg** [easychen/pushdeer#19]
不局限在手机接收推送通知，可以在任何联网的设备接收或发送通知，每个设备可以设置一个别名，可以把多个设备关联为一个群组，像群组key发送消息所有设备都可以接收到通知！
**MAC/Windows**：应用商店安装客户端用于接收或发送推送消息
**Chrome/Edge**：使用浏览器插件后台运行接收或发送推送通知
**WEB端**：登录站点设置一个key即可用浏览器接收推送通知

**Comment by easychen** [comment]
目前规划中的设备包括iOS（已上架）、Mac（已上架）和Android（开发中）。其他的端暂时不在日程表中。
