### ISSUE TITLE
自架服务器

### ISSUE THREAD

**Issue by SCUTJcfeng** [easychen/pushdeer#193]
不可以一个key发到多个绑定设备吗？我这边有一条消息发送到多个设备的需求，现在只能发多次http了

**Comment by easychen** [comment]
如果你把首页看完就不会有这个问题。

![image](https://github.com/easychen/pushdeer/assets/1294760/bd3a7a0d-2762-440b-9447-8a903b601bdc)

**Comment by SCUTJcfeng** [comment]
OK，不过我这边想省点代码，所以想一个key搞定，另外由于app不支持添加指定key，服务端代码稍微hack了一下
<img width="530" alt="image" src="https://github.com/easychen/pushdeer/assets/14869384/36824b48-ab45-4d6b-ae51-b604b7eb73cc">
<img width="629" alt="image" src="https://github.com/easychen/pushdeer/assets/14869384/f6f07f2a-1d9a-41ec-aebe-82bdc40bb52a">
