### ISSUE TITLE
[Bug]兼容<br>换行

### ISSUE THREAD

**Issue by GateCross** [easychen/pushdeer#199]
源码中api/app/Http/Controllers/PushDeerMessageController.php 
`$the_message['desp'] = $validated['desp'];`
#改为：
`$the_message['desp'] = preg_replace("/<br\s*\/?>/", "  \n", $validated['desp']);`
可以兼容markdown类型的<br>换行

<img width="635" alt="image" src="https://github.com/user-attachments/assets/e9b2ed01-f909-4c32-a111-bfff352237f9">

**Comment by easychen** [comment]
但是 <br>标签不是Markdown而是HTML吧？

**Comment by GateCross** [comment]
> 但是 标签不是Markdown而是HTML吧？

{
    "text":"测试",
    "desp":"测试 1<br>测试123",
    "type":"text"
}type使用 text 后者 markdown 都是无法换行
<img width="182" alt="image" src="https://github.com/user-attachments/assets/69951e53-c04d-4674-9538-75a849304457">

**Comment by easychen** [comment]
<br>是HTML，你用text/Markdown不能换行不是正常的吗？Markdown语法的换行是两次回车。

**Comment by GateCross** [comment]
> 是HTML，你用text/Markdown不能换行不是正常的吗？Markdown语法的换行是两次回车。

HTML 换行需要怎么处理一下比较好，我优化下传入参数
