### ISSUE TITLE
安装出现问题

### ISSUE THREAD

**Issue by vipazure6** [easychen/pushdeer#2]
@easychen 
程序只支持mariadb吗？我服务器只装了mysql5.5，如果我用mysql5.5版本是否可以？如果可以配置文件怎么修改
![20211224091118](https://user-images.githubusercontent.com/86450975/147303733-e26fe1ba-c844-48f1-a87e-b831328c6c14.png)

**Comment by easychen** [comment]
提示信息是你电脑上3306端口已经有服务了，可以把对应的服务停掉再启动。或者把docker-compose中的3306都改成3307。如果要在docker容器中使用本地电脑上的mysql，可以参考docker文档。
