### ISSUE TITLE
[app]生成key之后，焦点如果在input内，无法收回键盘

### ISSUE THREAD

**Issue by angiie** [easychen/pushdeer#21]
生成key之后，焦点如果在input内，无法收回键盘

进行重置或者新添加key，之后焦点仍然在input上

建议给键盘设置一个键盘折叠

**Comment by Goal75KG** [comment]
点击两次旁边的小箭头可以收回，但是麻烦，同意你的意见，建议生成key之后触发一个状态，让iOS键盘上显示完成按钮，以便关闭键盘

**Comment by easychen** [comment]
ff7325ccd392a075b4e4e4f6f02eaaa52464920c 已修复该问题。
