### ISSUE TITLE
push 内容正常可以输出, 但是推送到设备是?????

### ISSUE THREAD

**Issue by passwii** [easychen/pushdeer#23]
1. 用python 做了一个脚本 并且push通知到设备上, 显示??????
![image](https://user-images.githubusercontent.com/36389687/150463593-47da5ef3-27d3-4b4b-80c2-d527cc0851ad.png)
2. 用print 打印输出一下是否乱码, 终端显示正常, 并且复制url 到浏览器可以正常打开推送正常
<img width="1195" alt="image" src="https://user-images.githubusercontent.com/36389687/150463656-cfb06448-6725-4117-b8d3-939e9afbbe94.png">

**Comment by easychen** [comment]
URL 里边的中文需要通过 urlencode 等函数进行编码。chrome会自动给地址栏的中文编码解码，所以可以直接粘贴

**Comment by passwii** [comment]
OK, thanks :)

**Comment by gaoliang** [comment]
@passwii 封装了个Python SDK，可以试一下 https://github.com/gaoliang/pypushdeer
