### ISSUE TITLE
#号后内容被吞

### ISSUE THREAD

**Issue by XYZliang** [easychen/pushdeer#32]
当发送的消息包含#时，#后面的所有内容会被吞掉
如果内容开头是#，则直接报错 "The text must be a string."
本意输出一个#，就会出现以上错误。
<img width="957" alt="image" src="https://user-images.githubusercontent.com/59312540/151299004-6b797369-394f-41e5-aa42-207c5a09cd73.png">
如果内容是123#456#789，通知端只能收到123，#后全部没了
必须发送%23，即把#编码后，才能发送正常
<img width="1014" alt="image" src="https://user-images.githubusercontent.com/59312540/151298859-42494e1b-42f7-44aa-b6a6-4bb6cb2cea80.png">

**Comment by XYZliang** [comment]
如果对text内容强制编码的话，虽然#号的问题能解决，但是换行需要用的0%A也会被编码，导致通知里得到的也是0%A。
<img width="660" alt="image" src="https://user-images.githubusercontent.com/59312540/151299861-1dc4926d-42ec-4c01-88ec-04eb51269a98.png">
<img width="660" alt="image" src="https://user-images.githubusercontent.com/59312540/151299901-4d6d7026-6670-4222-bf7b-0ddda1abdd0a.png">
如果不编码，那么#号后的内容又没了
<img width="1206" alt="image" src="https://user-images.githubusercontent.com/59312540/151300081-cb133586-f171-4dae-a6b8-c7ca23d98c57.png">

**Comment by easychen** [comment]
在强制编码的情况下，换行本身就会被替换为%0A，不用手工替换了。
