### ISSUE TITLE
后续自建服务器的询问

### ISSUE THREAD

**Issue by cyy5358** [easychen/pushdeer#34]
首先谢谢各位开发者的工作，pushdeer 这个 app 很好用！

我会有个小担心，以后用户多了之后，`api2.pushdeer.com/message/push/` 服务器会不会有瓶颈呢。

我在安卓端看到了警告 `"由于厂商推送设备服务限制，暂时不支持更换为自建 PushDeer 服务器"`

具体是什么限制呢？是推送服务器的 IP 吗？

如果开发者搭建自己服务器并且申请自己的开发者appid，这样还会有问题吗？

非常喜欢 pushdeer 这个工具！练丹人士一定会狂喜

**Comment by easychen** [comment]
"由于厂商推送设备服务限制，暂时不支持更换为自建 PushDeer 服务器" 这句话的意思是，你需要重新编译自己的客户端并配置服务器端才能实现自架。

目前android客户端采用MiPush推送，需要有企业资质的用户去小米开发者平台申请权限并获得AppSecret。然后重新编译客户端才能接收推送。

具体的过程我们提供了文档 https://github.com/easychen/pushdeer/blob/main/doc/%E5%AE%89%E8%A3%85%E6%96%87%E6%A1%A3.md
