### ISSUE TITLE
android收到通知点击通知栏无反应，不跳进pushdeer内

### ISSUE THREAD

**Issue by mazdampv** [easychen/pushdeer#35]
我的小米11Pro，能正常收到通知，但是点击通知栏无法跳转通知详情

**Comment by ZainCheung** [comment]
问题一样
测试机型：RedMi K40 (MIUI13.0.2稳定版 Android12)

**Comment by easychen** [comment]
> 问题一样 测试机型：RedMi K40 (MIUI13.0.2稳定版 Android12)

我用的机器是 RedMi K30Pro  MIUI12 Android 11，没有遇到这个问题 😅  

不知道是不是 MIUI13 特有的问题，还是通知设置的问题？附几张设置图

![image](https://user-images.githubusercontent.com/1294760/151321997-d293a90c-cf47-4bf3-98f0-dc3ae60c2041.png)

![image](https://user-images.githubusercontent.com/1294760/151322026-6fc6ce59-1b2a-48ab-a2f2-e733ebbdd8c5.png)

**Comment by laphylee** [comment]
@easychen  也遇到了相同的问题。红米K30Pro, 系统：MIUI13 V13.0.0.1.5.Dev. 通知设置和上图一样。

**Comment by easychen** [comment]
> @easychen 也遇到了相同的问题。红米K30Pro, 系统：MIUI13 V13.0.0.1.5.Dev. 通知设置和上图一样。

看来是MIUI13不兼容的可能性比较大，稍后我们测试下。

**Comment by alone-wolf** [comment]
因为小米那边偷懒，现在只做到了点击通知打开主界面并显示消息列表，如果到这个程度那就是没有问题；而假如是点击通知条目没反应，那指定是小米的锅了，建议要么坑杀金凡，要么拉mipush团队祭天🐶

**Comment by PeterChen1997** [comment]
+ 点击后无反应

**Comment by easychen** [comment]
终于把这个问题修复了，需要使用最新版的 MiPush SDK  😂  请到这里下载最新apk https://github.com/easychen/pushdeer/releases/tag/android1.0beta
