### ISSUE TITLE
服务器搭建开发环境时候报错：received unexpected HTTP status: 500

### ISSUE THREAD

**Issue by hsinyan7** [easychen/pushdeer#36]
```
ERROR: Service 'app' failed to build: error pulling image configuration: received unexpected HTTP status: 500 Internal Server Error
```

![报错截图](https://user-images.githubusercontent.com/44678541/151586751-2bffb066-95a9-411f-994c-efcbf7ee7e07.jpg)

尝试更换docker源后问题依旧存在

**Comment by easychen** [comment]
先直接 `docker pull webdevops/php-apache:8.0` 一遍试试？

**Comment by hsinyan7** [comment]
> 先直接 `docker pull webdevops/php-apache:8.0` 一遍试试？

是的，昨天切到docker国外源后，运行这个命令就可以正常拉取了
