### ISSUE TITLE
Android版本消息格式为markdown时，悬浮通知和通栏不会渲染

### ISSUE THREAD

**Issue by yaojia25** [easychen/pushdeer#38]
机型小米10 Pro，当消息类型为markdown时，悬浮通知和通知栏里不会渲染markdown，显示的是消息源码，只有在应用里面才会渲染显示。

不知道这个可不可以优化。

**Comment by easychen** [comment]
悬浮通知和通知栏是不能使用Markdown的，较好的解决方案是在 text中传纯文本，在 desp 中传 markdown。这样标题和内容显示都Ok。

PS：Android 目前显示 desp 有点问题，稍后修复。
