### ISSUE TITLE
Android中URL推送消息时，收到的内容只包含text，没有desp

### ISSUE THREAD

**Issue by Muaoue** [easychen/pushdeer#40]
不知道是不是我设备没有添加成功的原因，还有就是server酱中可以渲染emoji，Pushdeer里面没法渲染
![image](https://user-images.githubusercontent.com/98643797/151659642-6ad0131b-842c-42e7-84ff-b0cd700b1648.png)

**Comment by easychen** [comment]
目前 Android 的 desp显示的确做丢了，稍后修复。Server酱用的是网页渲染，和PushDeer的原生渲染不一样。但我记得PushDeer是可以直接输入emoji的，不用转义。

**Comment by easychen** [comment]
最新版的Android客户端已经修复了这个问题。可在本仓库的 release 页面下载。
