### ISSUE TITLE
希望能尽快适配macOS 10

### ISSUE THREAD

**Issue by tangspoon66** [easychen/pushdeer#43]
V11 （Big Sur）有太多bug，大部分都是在用macOS 10.+（Catalina）的，希望能尽快适配。感谢！

**Comment by Hext123** [comment]
目前 macOS 版本是用 Mac Catalyst 实现的, 也就是说跟 iOS 是同一套代码, 
目前项目中使用了很多 iOS 14 才有的特性, 所以 macOS 也只能支持到 11.
(macOS 11 系统中内置的 Catalyst 等同于 iOS 14)

综上所述, 可能暂时不会支持到 macOS 10.x
