### ISSUE TITLE
编译成二进制

### ISSUE THREAD

**Issue by iranee** [easychen/pushdeer#44]
不知道将来会不会编译成二进制，适配arm、x64机型，就像bark server那样一个文件即可

**Comment by easychen** [comment]
> 不知道将来会不会编译成二进制，适配arm、x64机型，就像bark server那样一个文件即可

官方的API没有相关规划，不过社区有Go版本的基础实现，应该可以自己编译成二进制 https://github.com/iepngs/pushdeer-backend-go
