### ISSUE TITLE
iOS 消息页面更新不及时

### ISSUE THREAD

**Issue by yangmqglobe** [easychen/pushdeer#45]
如果 APP 当前在后台且正在消息 Tab，点击通知打开 APP，新收到的推送没有刷新出来，必须切换一下 Tab 才可以看到。

另外感觉消息 Tab 在第一个更符合使用习惯。

**Comment by fsnhljz** [comment]
附议，确实有延迟问题

**Comment by easychen** [comment]
ff7325ccd392a075b4e4e4f6f02eaaa52464920c 已经修复该问题，新版app正在上架中。
