### ISSUE TITLE
docker compose 安装提示找不到Dockerfile

### ISSUE THREAD

**Issue by willie91** [easychen/pushdeer#46]
![image](https://user-images.githubusercontent.com/32695308/152509700-fe10fb93-2ba0-4fb9-9c3f-6999c08e3b49.png)
作者你好，我用docker compose搭建的时候一直提示找不到这个文件，但是我打开路径这个文件是存在的不知道咋回事

**Comment by easychen** [comment]
在腾讯云ubuntu20.4 的服务器上无法复现，似乎可以认为是docker某些版本的bug？

![image](https://user-images.githubusercontent.com/1294760/152626838-8da68aab-0838-4d1f-854c-953019f0ec34.png)

```
sudo apt-get update && sudo apt-get install docker.io -y && sudo apt install docker-compose -y 
git clone https://gitee.com/easychen/pushdeer.git
cd  pushdeer/
sudo docker-compose -f docker-compose.self-hosted.yml up --build -d
```

**Comment by PikuZheng** [comment]
> ![image](https://user-images.githubusercontent.com/32695308/152509700-fe10fb93-2ba0-4fb9-9c3f-6999c08e3b49.png) 作者你好，我用docker compose搭建的时候一直提示找不到这个文件，但是我打开路径这个文件是存在的不知道咋回事

您左边红框里的是 dockerfile，右边说找不到的是Dockerfile

**Comment by willie91** [comment]
> > ![image](https://user-images.githubusercontent.com/32695308/152509700-fe10fb93-2ba0-4fb9-9c3f-6999c08e3b49.png) 作者你好，我用docker compose搭建的时候一直提示找不到这个文件，但是我打开路径这个文件是存在的不知道咋回事
> 
> 您左边红框里的是 dockerfile，右边说找不到的是Dockerfile

感谢..翻了好几次都没注意到这里，果然是这个的原因

**Comment by easychen** [comment]
查了一下，有些特定系统和版本的 docker  不支持小写的 dockerfile，已经改为 Dockerfile 以提升兼容性。
