### ISSUE TITLE
[iOS]在较窄屏幕上，url输入框宽度会超出屏幕

### ISSUE THREAD

**Issue by AndyZhuAZ** [easychen/pushdeer#47]
iPhone 13 Pro、iPhone 8 均有不同程度溢出。

![IMG_082271C60B45-1](https://user-images.githubusercontent.com/24852023/152534471-1baf56a9-b445-4c3a-880c-95d39e3f96e7.jpeg)

**Comment by easychen** [comment]
收到，下一个版本我们优化下。

**Comment by easychen** [comment]
ff7325ccd392a075b4e4e4f6f02eaaa52464920c 已修复，新版app正在上架中。
