### ISSUE TITLE
使用 iPad 生成的 Key 发起请求，通知却推送到 iPhone

### ISSUE THREAD

**Issue by Tymon42** [easychen/pushdeer#51]
遇到的问题如题，详细如下：
## 测试的 URL  
https://api2.pushdeer.com/message/push?pushkey=key&text=要发送的内容
## 系统版本    
iOS 15.0.1  
iPadOS 15.2  
## 操作流程和具体问题  
1. 一开始只下载了 iOS 端，请求的结果列在了 APP 的“消息”页，可以看到，但是手机不会有通知（没有 Banner，也没有提示音，通知权限也确定给了），多次删除设备重试无果，多次卸载 APP 重试无果；  
2. 又在 iPadOS 下载了，按照流程登录（设备页能看到手机设备，也能看到平板设备【有“（当前设备）”表示】）之后，用 iPad 生成的 Key 请求 URL，iPad 收不到通知（没有 Banner，也没有提示音，通知权限也确定给了），但是 iPhone 能够收到通知（Banner、提示音都有），多次尝试都是“使用 iPad 生成的 Key 发起请求，通知却推送到 iPhone”的结果。

**Comment by easychen** [comment]
key和生成它的设备没有关联，可以创建多个、重置和删除。设备页面注册的设备才决定了消息会往哪里推送。

iPad收不到通知，如果应用设置里边的通知权限没问题，试试卸载重装。

**Comment by Tymon42** [comment]
请问若是有多个注册设备，那么理论上是不是它们应该同时收到通知？

**Comment by Tymon42** [comment]
收到，谢谢。
