### ISSUE TITLE
如何支持长文本推送？

### ISSUE THREAD

**Issue by Iron-finger** [easychen/pushdeer#54]
发送较长的文本时，只能显示一行。![image](https://user-images.githubusercontent.com/59945118/153111075-7c1d7680-ceb4-4560-ac98-16456f7d2c76.png)

**Comment by easychen** [comment]
浮动通知本身有文字长度限制，长内容可以传给 desp 参数，这样点进应用以后可以在message里边看到更多内容。

**Comment by Iron-finger** [comment]
但是我看其他App可以支持长文本展开，就像即刻这种，是要接入厂商自带的推送协议吗？

**Comment by easychen** [comment]
> 但是我看其他App可以支持长文本展开，就像即刻这种，是要接入厂商自带的推送协议吗？

不太清楚，不同的厂商显示规则不同。实测MIUI12上PushDeer text加上换行可以显示两行文字左右。
