### ISSUE TITLE
ios15.2 重复推送

### ISSUE THREAD

**Issue by gaoliang** [easychen/pushdeer#56]
https://user-images.githubusercontent.com/18087875/153165948-7c9fa243-db54-40e6-b5e2-b3c516cc02aa.MP4

**Comment by easychen** [comment]
在我的iPad上测试了下没有重现问题。你看看注册了几个设备？会不会是 APP 和 Clip 都注册了，然后一个收到了一次推送？

**Comment by gaoliang** [comment]
我没有装App，只用过 Clip。 不过我的 Clip 有一段时间没打开了，测试的时候打开时似乎重新下载了，不知道是不是这个原因

**Comment by aka-ljf** [comment]
iphone13 pro ios 15.4 
clip同样问题
app clip 设备全部删除后重新添加仍无法解决

**Comment by easychen** [comment]
该问题因为gorush redis引擎导致，已更换引擎（ ed7d2565273ae7057bf28baa6ec8ef1bc31b7211 ）。使用自架服务端的同学请更新后台代码到最新版。
