### ISSUE TITLE
iphone无法显示系统通知，仅在app内有成功提示和记录

### ISSUE THREAD

**Issue by debeetle** [easychen/pushdeer#58]
iphone13 mini
ios 15.3
记得15.2好像有系统通知，这版系统没有了，不清楚是软件问题还是系统问题
期待回复

**Comment by easychen** [comment]
昨天的某个版本在未配置mipush参数时推送服务启动会失败。可以手动禁用下mipush或者拉取最新的默认配置文件。

**Comment by debeetle** [comment]
> iphone13 mini
> 
> ios 15.3
> 
> 记得15.2好像有系统通知，这版系统没有了，不清楚是软件问题还是系统问题
> 
> 期待回复

更新：

过了一夜问题消失了，但是我同时在ipad上也登录同一个账号后，新的问题是通知栏会推送两次。app内只有一次记录合乎逻辑。用的是apple clips

**Comment by easychen** [comment]
> > iphone13 mini
> > ios 15.3
> > 记得15.2好像有系统通知，这版系统没有了，不清楚是软件问题还是系统问题
> > 期待回复
> 
> 更新：
> 
> 过了一夜问题消失了，但是我同时在ipad上也登录同一个账号后，新的问题是通知栏会推送两次。app内只有一次记录合乎逻辑。用的是apple clips

这个问题我已经重现了，正在查原因

**Comment by easychen** [comment]
> > iphone13 mini
> > ios 15.3
> > 记得15.2好像有系统通知，这版系统没有了，不清楚是软件问题还是系统问题
> > 期待回复
> 
> 更新：
> 
> 过了一夜问题消失了，但是我同时在ipad上也登录同一个账号后，新的问题是通知栏会推送两次。app内只有一次记录合乎逻辑。用的是apple clips

经排查是 gorush 队列 redis引擎的问题，最新的配置文件已经更新，也可以手工换回 local 引擎。可参考 https://github.com/easychen/pushdeer/commit/ed7d2565273ae7057bf28baa6ec8ef1bc31b7211

**Comment by cheng2004237** [comment]
的确有这个问题，安卓版通知正常，苹果版没有任何通知
