### ISSUE TITLE
有没群晖小白教程？

### ISSUE THREAD

**Issue by fsnhljz** [easychen/pushdeer#60]
感觉很好用，能不装APP，那就是可以不用bark了，但完全看不懂，百度没有教程。

**Comment by easychen** [comment]
没有群晖，所以没有教程。但你可以搜索下群晖如何通过docker-compose安装应用。区别只是命令不同。剩下的可以看B站的教学视频。https://www.bilibili.com/video/BV1pR4y1j7ef
