### ISSUE TITLE
在iPadOS15.3中无法登入（-4）：无法建立与该服务器的安全连接

### ISSUE THREAD

**Issue by mcwuguodadi** [easychen/pushdeer#63]
通过apple正常登入后提示登入失败（-4）URLSessionTask failed with error:发生SSL错误，无法建立与该服务器的安全连接。

设备：iPad 5
系统：iPadOS 15.3
软件版本：1.1.1

**Comment by easychen** [comment]
1. 使用的是官方版还是自架版？
2. 如果是自架版，服务器的https证书是否正确？

**Comment by mcwuguodadi** [comment]
PushDeer客户端，并不是PushDeer自架板
![IMG_4744](https://user-images.githubusercontent.com/82522552/153840238-f274d15a-51cc-4671-a019-d16cf8ca73e7.PNG)

**Comment by easychen** [comment]
> PushDeer客户端，并不是PushDeer自架板 ![IMG_4744](https://user-images.githubusercontent.com/82522552/153840238-f274d15a-51cc-4671-a019-d16cf8ca73e7.PNG)

检查了官方的证书没有过期，问题也无法重现。是不是你用的网络代理关了或者换了？

**Comment by mcwuguodadi** [comment]
没开任何的代理呐……
