### ISSUE TITLE
ios 15.3.1无法收到通知

### ISSUE THREAD

**Issue by cheng2004237** [easychen/pushdeer#66]
ios 15.3.1无法收到通知
通知权限已全部打开，仍然无法收到推送。
官方版，非自架版。
使用同一苹果id登录，安卓版可以收到通知，ios则不行。

**Comment by easychen** [comment]
确认注册了当前设备吗？

目前推送服务是正常的，如果不是苹果服务器端的短暂不可用，应该就是客户端设置不太对，实在不行删掉重装试试？
