### ISSUE TITLE
个人安卓用户是不是无法使用自建服务器？

### ISSUE THREAD

**Issue by cc1990** [easychen/pushdeer#67]
[安装文档](https://github.com/easychen/pushdeer/blob/main/doc/%E5%AE%89%E8%A3%85%E6%96%87%E6%A1%A3.md)

    你好，在看[安装文档]的时候，有个问题想问一下：

    苹果用户可以使用iso自架版客户端通过配置endpoint_url的方式完成自架服务器的推送，安卓用户为啥不能也通过这种方式完成自架服务器的推送？

    我是一个NAS的用户，打算自架pushdeer服务器，同时也是安卓用户。现在无法通过注册小米开发者（**企业认证**）创建应用获取包名和AppSecret的方式编译Android客户端，所以只能使用打包好的Android客户端和pushdeer.com的服务端完成推送么？

**Comment by easychen** [comment]
mipush是不行的，但Android项目的核心同学在准备一个websocket的方案。

**Comment by cc1990** [comment]
好的，谢谢，期待websocket的方案

**Comment by PikuZheng** [comment]
>现在无法通过注册小米开发者（**企业认证**）创建应用获取包名和AppSecret的方式编译Android客户端，所以只能使用打包好的Android客户端和pushdeer.com的服务端完成推送么？
> 
我页一直在等安卓的自建服务器方案。。。顺便吐槽一下以前小米是允许注册个人开发者的（我在2018年就注册了mipush的appid。不知道现在还能不能用了

**Comment by easychen** [comment]
> > 现在无法通过注册小米开发者（**企业认证**）创建应用获取包名和AppSecret的方式编译Android客户端，所以只能使用打包好的Android客户端和pushdeer.com的服务端完成推送么？
> 
> 我页一直在等安卓的自建服务器方案。。。顺便吐槽一下以前小米是允许注册个人开发者的（我在2018年就注册了mipush的appid。不知道现在还能不能用了

可以，不过需要自己改一下包名，重新编译下客户端。

**Comment by alone-wolf** [comment]
明确一下昂，单纯的基于websocket整一个推送功能可太简单了，在不考虑安全性和各种sdk接入的情况下；目前单独的推送已经过验证，忙过这段时间调一下接入目测就能差不多了

**Comment by cc1990** [comment]
> 明确一下昂，单纯的基于websocket整一个推送功能可太简单了，在不考虑安全性和各种sdk接入的情况下；目前单独的推送已经过验证，忙过这段时间调一下接入目测就能差不多了

websocket只服务于一个推送功能有点大材小用的感觉 😂

**Comment by zhuweitung** [comment]
需求+1
