### ISSUE TITLE
多用户推送问题

### ISSUE THREAD

**Issue by lowwor** [easychen/pushdeer#68]
我在我的手机登录，生成了我的key。但是有另一个人的设备也需要推送，但我没法在那个设备上登录。能否支持另外的人登录后，手动输入我的key，或者发送请求里支持key列表？

**Comment by easychen** [comment]
只要知道对方的Key就可以直接通过API进行推送，多个key多次调用就好了。

**Comment by lowwor** [comment]
主要key多了的话有点麻烦，比如10个人，那就要请求10次了。

**Comment by easychen** [comment]
> 主要key多了的话有点麻烦，比如10个人，那就要请求10次了。

https://github.com/easychen/pushdeer/commit/d1f1940bd2533d4eeced4eec8ab678b7d5e7ec32
