### ISSUE TITLE
一加8注册设备时弹窗提示: 本设备在厂商推送服务注册失败.

### ISSUE THREAD

**Issue by shijinlong12** [easychen/pushdeer#70]
**问题描述**
使用 **一加8** 安装 **安卓测试版app后(https://github.com/easychen/pushdeer/releases/download/android1.0alpha/pushdeer-alpha-4.apk)**, 微信登录和生成密钥的过程都没有问题, 但是 **在注册设备时弹窗提示: 本设备在厂商推送服务注册失败**.

**重现**

重现步骤:

1. 打开PushDeer安卓版应用.
2. 切换到设备页, 点击右上角的 + 号.
3. 弹窗提示错误, 弹窗内容如下
![f6816b9e7a235ae8fc9827f1385c65a](https://user-images.githubusercontent.com/40626840/154881398-4251ab99-5d82-4952-bfb2-365c3143f252.jpg)

**期望的结果**

**截图**

**环境和版本**
 - 系统版本: ![c19f17b95ca595562778b1011a94529](https://user-images.githubusercontent.com/40626840/154881505-20773aa0-9ac2-4612-9522-324078cf0aa8.jpg)
 - ![6b0fd5fc9bdf1bb47e424ac624dfc0a](https://user-images.githubusercontent.com/40626840/154882108-f5ddd0c6-7385-413c-a547-3be6a23cb5e8.jpg)

 - 软件版本： 官方安卓测试版app
 ![19f993b7bf926d6fd38bdf5d2b63f8e](https://user-images.githubusercontent.com/40626840/154881583-8f7e477a-33e2-467e-817b-1e77c5882a37.jpg)

**软件权限**
- 通知权限
![8e58a65d65f77f80abc4b62034635cc](https://user-images.githubusercontent.com/40626840/154881709-48ac9e1e-ff6e-465b-a884-5ef98957d8c1.jpg)
- 应用权限
![c9c02afe0b785821936bf21e519fbce](https://user-images.githubusercontent.com/40626840/154881751-8ee5faee-9dca-445e-9540-6f0bf17dd80a.jpg)
- 联网权限
![a347f80f28dfc7b769b829396df9f58](https://user-images.githubusercontent.com/40626840/154881769-065e1f31-0a00-4844-9f94-aa3abaf9614a.jpg)

 **收不到消息请填写**
 - 是否注册设备: [否]
 - 是否注册当前设备: [否]（ 设备页面有设备名称后显示「当前设备」 )
 - 是否开通通知权限: [是]
 - 是否开重装过应用: [是]
 - APP和轻APP（Clip）是否分别都注册过设备: [否]
 
 - 注册设备页面截图
 - 应用通知设置页面截图
 
> 大部分用户在尝试删除重装应用后，可以修复问题，您也可以试试 
删除重装和关闭再打开都无法解决.
 
**其他说明**

**Comment by easychen** [comment]
这个错误提示是因为MiPush无法获取到设备token并注册服务，我们排查起来比较困难，一直在定位原因。之前有非小米机型用户也遇到过，似乎重装后再点击就好了。😅

**Comment by shijinlong12** [comment]
> 这个错误提示是因为MiPush无法获取到设备token并注册服务，我们排查起来比较困难，一直在定位原因。之前有非小米机型用户也遇到过，似乎重装后再点击就好了。😅

我也重装过了 但是还是一样. 那我试试别的手机

**Comment by Eliauk365** [comment]
Realme GT 也遇到同样的问题

**Comment by FranzKafkaYu** [comment]
我是小米手机，同样遇到了这个问题，请问有解决办法吗

**Comment by FranzKafkaYu** [comment]
> 我是小米手机，同样遇到了这个问题，请问有解决办法吗

小米手机，实测卸载应用后重新进行安装解决该问题，感谢~

**Comment by coolmian** [comment]
我也是添加不了，型号：荣耀V30pro
