### ISSUE TITLE
想往后付费，现阶段一分钟内能发多少条信息呢？

### ISSUE THREAD

**Issue by bequt** [easychen/pushdeer#79]
想往后付费，现阶段一分钟内能发多少条信息呢？

**Comment by bequt** [comment]
当然现在已经是方糖会员用户，目前看到方糖这边是一分钟限制发50条以内。

**Comment by easychen** [comment]
现在PushDeer在线版是一分钟60次api请求，自架版可以在配置文件里边随便改  https://github.com/easychen/pushdeer/blob/2310265c7703fc7d1dcee555e02d30767af7384b/api/.env.example#L67
