### ISSUE TITLE
[建议]客户端增加一键清空消息功能

### ISSUE THREAD

**Issue by xiaobinHub** [easychen/pushdeer#82]
客户端上（特别是MacBook客户端）删除消息比较麻烦，消息太多时很麻烦。希望在消息列表添加“一键清空”功能。
谢谢！

**Comment by easychen** [comment]
后端接口已经加上了，客户端后续版本再加吧。

**Comment by Hext123** [comment]
macOS 1.5 版本 消息已经支持鼠标右键删除,

一键清空功能等待下一个版本更新

**Comment by Hext123** [comment]
iOS/iPadOS/macOS 客户端已支持一键清空消息

(1分钟内连续删除两条消息会触发清空提示)
