### ISSUE TITLE
[Bug]1.3 iOS 无法打开server酱发送的信息详情

### ISSUE THREAD

**Issue by nov12** [easychen/pushdeer#87]
**描述你遇到的Bug**
server酱发送的信息无法点击详情打开。上一版本可跳转默认浏览器打开。

**重现**

重现步骤:
1.将server酱配置通道为pushdeer。
2.通过server酱发送信息测试即可。

**环境和版本**
 - 系统:  iOS
 - 版本：官方版1.3

**手机或电脑的的详细信息**
 - Device: iPhone 12Pro
 - OS: 15.3.1

 **可以收到消息**
 - 是否注册设备: [是]
 - 是否注册当前设备: [是]（ 设备页面有设备名称后显示「当前设备」 ）
 - 是否开通通知权限: [是]
 - 是否开重装过应用: [是]
 - APP和轻APP（Clip）是否分别都注册过设备: [是]
 

**其他说明**

Mac 端可以打开详情，但是软件内系统不识别为超链接了——鼠标停放时指针不再变为手。

**Comment by easychen** [comment]
感谢反馈，我们已经重现了该问题，将尽快修复。

**Comment by 9o8i7u** [comment]
系统: iOS
版本：官方版1.3

消息列表  很卡，几乎卡死，不能上下翻动历史消息。 “消息”频道几乎是死机了，但可以切换到“设备”、“KEY”、“设置”等频道。
