### ISSUE TITLE
PushDeer自架版IOS客户端更新以后，使用APPLE登录时，显示-4的错误（接口报错500）

### ISSUE THREAD

**Issue by jsbyl** [easychen/pushdeer#89]
今天PushDeer自架版IOS客户端更新以后，使用APPLE登录时，显示-4的错误（接口报错500）

**Comment by easychen** [comment]
请按调试说明提供报错信息 https://github.com/easychen/pushdeer/blob/main/doc/%E8%B0%83%E8%AF%95%E6%96%87%E6%A1%A3.md

**Comment by jsbyl** [comment]
pushdeer-app-1      | docker.vm:80 172.28.144.1 - - [04/Mar/2022:14:42:20 +0800] "POST /login/idtoken?idToken=eyJraWQiOiJZdXlYb1kiLCJhbGciOiJSUzI1NiJ9.eyJpc3MiOiJodHRwczovL2FwcGxlaWQuYXBwbGUuY29tIiwiYXVkIjoiY29tLnB1c2hkZWVyLnNlbGYuaW9zIiwiZXhwIjoxNjQ2NDYyNTQyLCJpYXQiOjE2NDYzNzYxNDIsInN1YiI6IjAwMDI0MS41Mjc1Y2E4M2YwNzU0ZjY0YjMwNjc3NTNiZjZhOTE4Ni4wMTAxIiwiY19oYXNoIjoiWGNOUUtkc2NXakdaaWd6NzhfYXhjdyIsImVtYWlsIjoiMTM5MDczMTc4NjdAMTM5LmNvbSIsImVtYWlsX3ZlcmlmaWVkIjoidHJ1ZSIsImF1dGhfdGltZSI6MTY0NjM3NjE0Miwibm9uY2Vfc3VwcG9ydGVkIjp0cnVlfQ.IiCauTcSPsqa-2a72UaT1dDulXVIKs9tiyMEDvnzNWlM1cKbBilQ4ASNUezc6bmgdd_dnzrTuKLvnrgNvQ5_lz4U-mCatdNY9dC75zgUj0VpTGb2CVoPgQlpV5gGoD6kQGMKLjKZblH67q1klmp3qdOccc3E8TQPt9qwRAtHSXidkYsTb82l85jFsF5sCBl8pzNzB_IGrhfGkOQgY28vwlFiMHKx1Ps04-LF6I0lGs8Ik-oK-KKugDIZy2sjYcQE76Tfrbaypz8jet5mKbdfbW_rsij_GhzCk8QFBoQpeCyCKjqs1jseVWBeb9ohIJSONNUcnADuwLfjLlGgNAP3WA HTTP/1.1" 500 6906 "-" "PushDeer/1.4 (com.pushdeer.self.ios; build:1; iOS 15.3.1) Alamofire/5.5.0"
pushdeer-app-1      | [httpd:access] 222.247.54.30:80 - - 172.28.144.1 - - [04/Mar/2022:14:42:20 +0800] "POST /login/idtoken?idToken=eyJraWQiOiJZdXlYb1kiLCJhbGciOiJSUzI1NiJ9.eyJpc3MiOiJodHRwczovL2FwcGxlaWQuYXBwbGUuY29tIiwiYXVkIjoiY29tLnB1c2hkZWVyLnNlbGYuaW9zIiwiZXhwIjoxNjQ2NDYyNTQyLCJpYXQiOjE2NDYzNzYxNDIsInN1YiI6IjAwMDI0MS41Mjc1Y2E4M2YwNzU0ZjY0YjMwNjc3NTNiZjZhOTE4Ni4wMTAxIiwiY19oYXNoIjoiWGNOUUtkc2NXakdaaWd6NzhfYXhjdyIsImVtYWlsIjoiMTM5MDczMTc4NjdAMTM5LmNvbSIsImVtYWlsX3ZlcmlmaWVkIjoidHJ1ZSIsImF1dGhfdGltZSI6MTY0NjM3NjE0Miwibm9uY2Vfc3VwcG9ydGVkIjp0cnVlfQ.IiCauTcSPsqa-2a72UaT1dDulXVIKs9tiyMEDvnzNWlM1cKbBilQ4ASNUezc6bmgdd_dnzrTuKLvnrgNvQ5_lz4U-mCatdNY9dC75zgUj0VpTGb2CVoPgQlpV5gGoD6kQGMKLjKZblH67q1klmp3qdOccc3E8TQPt9qwRAtHSXidkYsTb82l85jFsF5sCBl8pzNzB_IGrhfGkOQgY28vwlFiMHKx1Ps04-LF6I0lGs8Ik-oK-KKugDIZy2sjYcQE76Tfrbaypz8jet5mKbdfbW_rsij_GhzCk8QFBoQpeCyCKjqs1jseVWBeb9ohIJSONNUcnADuwLfjLlGgNAP3WA HTTP/1.1" 500 bytesIn:1111 bytesOut:6906 reqTime:1
pushdeer-app-1      | [php-fpm:access] 127.0.0.1 -  04/Mar/2022:14:42:20 +0800 "POST /index.php?idToken=eyJraWQiOiJZdXlYb1kiLCJhbGciOiJSUzI1NiJ9.eyJpc3MiOiJodHRwczovL2FwcGxlaWQuYXBwbGUuY29tIiwiYXVkIjoiY29tLnB1c2hkZWVyLnNlbGYuaW9zIiwiZXhwIjoxNjQ2NDYyNTQyLCJpYXQiOjE2NDYzNzYxNDIsInN1YiI6IjAwMDI0MS41Mjc1Y2E4M2YwNzU0ZjY0YjMwNjc3NTNiZjZhOTE4Ni4wMTAxIiwiY19oYXNoIjoiWGNOUUtkc2NXakdaaWd6NzhfYXhjdyIsImVtYWlsIjoiMTM5MDczMTc4NjdAMTM5LmNvbSIsImVtYWlsX3ZlcmlmaWVkIjoidHJ1ZSIsImF1dGhfdGltZSI6MTY0NjM3NjE0Miwibm9uY2Vfc3VwcG9ydGVkIjp0cnVlfQ.IiCauTcSPsqa-2a72UaT1dDulXVIKs9tiyMEDvnzNWlM1cKbBilQ4ASNUezc6bmgdd_dnzrTuKLvnrg" 500 /app/api/public/index.php 1027.555 8192 18.49%

**Comment by jsbyl** [comment]
![2d1e2bcdbf6d1949de2dfd83bd0723e](https://user-images.githubusercontent.com/34727765/156713166-59122654-780a-4396-a1bf-ede5311f9e5a.jpg)

**Comment by jsbyl** [comment]
{'code': 0, 'content': {'result': ['{"counts":1,"logs":[],"success":"ok"}']}}
虽然APP没有登录成功，但是发送信息的时候，代码里面显示成功，服务端报错。APP没有任何显示。
pushdeer-app-1      | NOTICE: PHP message: push error{"counts":1,"logs":[],"success":"ok"}
pushdeer-app-1      | [Fri Mar 04 14:44:45.421002 2022] [proxy_fcgi:error] [pid 123:tid 140704441259776] [client 172.28.144.1:2287] AH01071: Got error 'PHP message: push error{"counts":1,"logs":[],"success":"ok"}'
pushdeer-app-1      | docker.vm:80 172.28.144.1 - - [04/Mar/2022:14:44:45 +0800] "GET /message/push?pushkey=PDU1TCP63u8RfwWFtazi7LSKYbbBds2VvvVEe&text=%E6%B5%8B%E8%AF%9536 HTTP/1.1" 200 343 "-" "python-requests/2.27.1"
pushdeer-app-1      | [httpd:access] 222.247.54.30:80 - - 172.28.144.1 - - [04/Mar/2022:14:44:45 +0800] "GET /message/push?pushkey=PDU1TCP63u8RfwWFtazi7LSKYbbBds2VvvVEe&text=%E6%B5%8B%E8%AF%9536 HTTP/1.1" 200 bytesIn:229 bytesOut:343 reqTime:0
pushdeer-app-1      | [php-fpm:access] 127.0.0.1 -  04/Mar/2022:14:44:45 +0800 "GET /index.php?pushkey=PDU1TCP63u8RfwWFtazi7LSKYbbBds2VvvVEe&text=%E6%B5%8B%E8%AF%9536" 200 /app/api/public/index.php 71.494 6144 83.92%

**Comment by easychen** [comment]
请修改你使用的 `docker-compose` 文件，将 `APP_DEBUG` 设置为 `true`。

然后通过 postman 等工具发送请求到：

/login/idtoken?idToken=eyJraWQiOiJZdXlYb1kiLCJhbGciOiJSUzI1NiJ9.eyJpc3MiOiJodHRwczovL2FwcGxlaWQuYXBwbGUuY29tIiwiYXVkIjoiY29tLnB1c2hkZWVyLnNlbGYuaW9zIiwiZXhwIjoxNjQ2NDYyNTQyLCJpYXQiOjE2NDYzNzYxNDIsInN1YiI6IjAwMDI0MS41Mjc1Y2E4M2YwNzU0ZjY0YjMwNjc3NTNiZjZhOTE4Ni4wMTAxIiwiY19oYXNoIjoiWGNOUUtkc2NXakdaaWd6NzhfYXhjdyIsImVtYWlsIjoiMTM5MDczMTc4NjdAMTM5LmNvbSIsImVtYWlsX3ZlcmlmaWVkIjoidHJ1ZSIsImF1dGhfdGltZSI6MTY0NjM3NjE0Miwibm9uY2Vfc3VwcG9ydGVkIjp0cnVlfQ.IiCauTcSPsqa-2a72UaT1dDulXVIKs9tiyMEDvnzNWlM1cKbBilQ4ASNUezc6bmgdd_dnzrTuKLvnrgNvQ5_lz4U-mCatdNY9dC75zgUj0VpTGb2CVoPgQlpV5gGoD6kQGMKLjKZblH67q1klmp3qdOccc3E8TQPt9qwRAtHSXidkYsTb82l85jFsF5sCBl8pzNzB_IGrhfGkOQgY28vwlFiMHKx1Ps04-LF6I0lGs8Ik-oK-KKugDIZy2sjYcQE76Tfrbaypz8jet5mKbdfbW_rsij_GhzCk8QFBoQpeCyCKjqs1jseVWBeb9ohIJSONNUcnADuwLfjLlGgNAP3WA

将页面显示的500错误信息贴到这里。

**Comment by jsbyl** [comment]
打开APP_DEBUG参数了，不知道怎么用postman。。。
pushdeer-app-1      | docker.vm:80 172.28.144.1 - - [04/Mar/2022:14:55:02 +0800] "POST /login/idtoken?idToken=eyJraWQiOiI4NkQ4OEtmIiwiYWxnIjoiUlMyNTYifQ.eyJpc3MiOiJodHRwczovL2FwcGxlaWQuYXBwbGUuY29tIiwiYXVkIjoiY29tLnB1c2hkZWVyLnNlbGYuaW9zIiwiZXhwIjoxNjQ2NDYzMzA0LCJpYXQiOjE2NDYzNzY5MDQsInN1YiI6IjAwMDI0MS41Mjc1Y2E4M2YwNzU0ZjY0YjMwNjc3NTNiZjZhOTE4Ni4wMTAxIiwiY19oYXNoIjoiam54MmxBeTE5M0xJXzdUaU94LTI1QSIsImVtYWlsIjoiMTM5MDczMTc4NjdAMTM5LmNvbSIsImVtYWlsX3ZlcmlmaWVkIjoidHJ1ZSIsImF1dGhfdGltZSI6MTY0NjM3NjkwNCwibm9uY2Vfc3VwcG9ydGVkIjp0cnVlfQ.V0UjW0ZVxYnq4_heEkO4WBCT1a-0RzaIy1Ev85KmYhk7_rWnfgZDMAq-oqP0i-8q8Oc9e5lrxW5BKq75-vTUlNbkCjSLku4eGPC3ItLtF9QFLovrwvhnUaJ3dkvbX04FkliL1v5SNDmmHMoPT05JRoBuV3YXbw4fwuhGgCG-6cMuIWvQ31u0QXZ51UwgHltOGZJwvkK_uqUN6zX72gCHrfhlcBlH74sYIri5p-DjlBDW1NYuUmrEXBKToVRdOc-763XXw_Ry2BYoKzaRXW-B3HzV-jkHIIhvvU05GLi9E6iYJWUm7igUjdCDErAS9nnWze3o7PEiRYOmiOGtFubQaA HTTP/1.1" 500 606086 "-" "PushDeer/1.4 (com.pushdeer.self.ios; build:1; iOS 15.3.1) Alamofire/5.5.0"
pushdeer-app-1      | [httpd:access] 222.247.54.30:80 - - 172.28.144.1 - - [04/Mar/2022:14:55:02 +0800] "POST /login/idtoken?idToken=eyJraWQiOiI4NkQ4OEtmIiwiYWxnIjoiUlMyNTYifQ.eyJpc3MiOiJodHRwczovL2FwcGxlaWQuYXBwbGUuY29tIiwiYXVkIjoiY29tLnB1c2hkZWVyLnNlbGYuaW9zIiwiZXhwIjoxNjQ2NDYzMzA0LCJpYXQiOjE2NDYzNzY5MDQsInN1YiI6IjAwMDI0MS41Mjc1Y2E4M2YwNzU0ZjY0YjMwNjc3NTNiZjZhOTE4Ni4wMTAxIiwiY19oYXNoIjoiam54MmxBeTE5M0xJXzdUaU94LTI1QSIsImVtYWlsIjoiMTM5MDczMTc4NjdAMTM5LmNvbSIsImVtYWlsX3ZlcmlmaWVkIjoidHJ1ZSIsImF1dGhfdGltZSI6MTY0NjM3NjkwNCwibm9uY2Vfc3VwcG9ydGVkIjp0cnVlfQ.V0UjW0ZVxYnq4_heEkO4WBCT1a-0RzaIy1Ev85KmYhk7_rWnfgZDMAq-oqP0i-8q8Oc9e5lrxW5BKq75-vTUlNbkCjSLku4eGPC3ItLtF9QFLovrwvhnUaJ3dkvbX04FkliL1v5SNDmmHMoPT05JRoBuV3YXbw4fwuhGgCG-6cMuIWvQ31u0QXZ51UwgHltOGZJwvkK_uqUN6zX72gCHrfhlcBlH74sYIri5p-DjlBDW1NYuUmrEXBKToVRdOc-763XXw_Ry2BYoKzaRXW-B3HzV-jkHIIhvvU05GLi9E6iYJWUm7igUjdCDErAS9nnWze3o7PEiRYOmiOGtFubQaA HTTP/1.1" 500 bytesIn:1113 bytesOut:606086 reqTime:1
pushdeer-app-1      | [php-fpm:access] 127.0.0.1 -  04/Mar/2022:14:55:02 +0800 "POST /index.php?idToken=eyJraWQiOiI4NkQ4OEtmIiwiYWxnIjoiUlMyNTYifQ.eyJpc3MiOiJodHRwczovL2FwcGxlaWQuYXBwbGUuY29tIiwiYXVkIjoiY29tLnB1c2hkZWVyLnNlbGYuaW9zIiwiZXhwIjoxNjQ2NDYzMzA0LCJpYXQiOjE2NDYzNzY5MDQsInN1YiI6IjAwMDI0MS41Mjc1Y2E4M2YwNzU0ZjY0YjMwNjc3NTNiZjZhOTE4Ni4wMTAxIiwiY19oYXNoIjoiam54MmxBeTE5M0xJXzdUaU94LTI1QSIsImVtYWlsIjoiMTM5MDczMTc4NjdAMTM5LmNvbSIsImVtYWlsX3ZlcmlmaWVkIjoidHJ1ZSIsImF1dGhfdGltZSI6MTY0NjM3NjkwNCwibm9uY2Vfc3VwcG9ydGVkIjp0cnVlfQ.V0UjW0ZVxYnq4_heEkO4WBCT1a-0RzaIy1Ev85KmYhk7_rWnfgZDMAq-oqP0i-8q8Oc9e5lrxW5BK" 500 /app/api/public/index.php 1070.278 10240 21.49%
pushdeer-app-1      | docker.vm:80 172.28.144.1 - - [04/Mar/2022:14:56:07 +0800] "GET //login/idtoken?idToken=eyJraWQiOiJZdXlYb1kiLCJhbGciOiJSUzI1NiJ9.eyJpc3MiOiJodHRwczovL2FwcGxlaWQuYXBwbGUuY29tIiwiYXVkIjoiY29tLnB1c2hkZWVyLnNlbGYuaW9zIiwiZXhwIjoxNjQ2NDYyNTQyLCJpYXQiOjE2NDYzNzYxNDIsInN1YiI6IjAwMDI0MS41Mjc1Y2E4M2YwNzU0ZjY0YjMwNjc3NTNiZjZhOTE4Ni4wMTAxIiwiY19oYXNoIjoiWGNOUUtkc2NXakdaaWd6NzhfYXhjdyIsImVtYWlsIjoiMTM5MDczMTc4NjdAMTM5LmNvbSIsImVtYWlsX3ZlcmlmaWVkIjoidHJ1ZSIsImF1dGhfdGltZSI6MTY0NjM3NjE0Miwibm9uY2Vfc3VwcG9ydGVkIjp0cnVlfQ.IiCauTcSPsqa-2a72UaT1dDulXVIKs9tiyMEDvnzNWlM1cKbBilQ4ASNUezc6bmgdd_dnzrTuKLvnrgNvQ5_lz4U-mCatdNY9dC75zgUj0VpTGb2CVoPgQlpV5gGoD6kQGMKLjKZblH67q1klmp3qdOccc3E8TQPt9qwRAtHSXidkYsTb82l85jFsF5sCBl8pzNzB_IGrhfGkOQgY28vwlFiMHKx1Ps04-LF6I0lGs8Ik-oK-KKugDIZy2sjYcQE76Tfrbaypz8jet5mKbdfbW_rsij_GhzCk8QFBoQpeCyCKjqs1jseVWBeb9ohIJSONNUcnADuwLfjLlGgNAP3WA HTTP/1.1" 404 6838 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/98.0.4758.102 Safari/537.36"
pushdeer-app-1      | [httpd:access] 222.247.54.30:80 - - 172.28.144.1 - - [04/Mar/2022:14:56:07 +0800] "GET //login/idtoken?idToken=eyJraWQiOiJZdXlYb1kiLCJhbGciOiJSUzI1NiJ9.eyJpc3MiOiJodHRwczovL2FwcGxlaWQuYXBwbGUuY29tIiwiYXVkIjoiY29tLnB1c2hkZWVyLnNlbGYuaW9zIiwiZXhwIjoxNjQ2NDYyNTQyLCJpYXQiOjE2NDYzNzYxNDIsInN1YiI6IjAwMDI0MS41Mjc1Y2E4M2YwNzU0ZjY0YjMwNjc3NTNiZjZhOTE4Ni4wMTAxIiwiY19oYXNoIjoiWGNOUUtkc2NXakdaaWd6NzhfYXhjdyIsImVtYWlsIjoiMTM5MDczMTc4NjdAMTM5LmNvbSIsImVtYWlsX3ZlcmlmaWVkIjoidHJ1ZSIsImF1dGhfdGltZSI6MTY0NjM3NjE0Miwibm9uY2Vfc3VwcG9ydGVkIjp0cnVlfQ.IiCauTcSPsqa-2a72UaT1dDulXVIKs9tiyMEDvnzNWlM1cKbBilQ4ASNUezc6bmgdd_dnzrTuKLvnrgNvQ5_lz4U-mCatdNY9dC75zgUj0VpTGb2CVoPgQlpV5gGoD6kQGMKLjKZblH67q1klmp3qdOccc3E8TQPt9qwRAtHSXidkYsTb82l85jFsF5sCBl8pzNzB_IGrhfGkOQgY28vwlFiMHKx1Ps04-LF6I0lGs8Ik-oK-KKugDIZy2sjYcQE76Tfrbaypz8jet5mKbdfbW_rsij_GhzCk8QFBoQpeCyCKjqs1jseVWBeb9ohIJSONNUcnADuwLfjLlGgNAP3WA HTTP/1.1" 404 bytesIn:1557 bytesOut:6838 reqTime:0
pushdeer-app-1      | [php-fpm:access] 127.0.0.1 -  04/Mar/2022:14:56:07 +0800 "GET /index.php?idToken=eyJraWQiOiJZdXlYb1kiLCJhbGciOiJSUzI1NiJ9.eyJpc3MiOiJodHRwczovL2FwcGxlaWQuYXBwbGUuY29tIiwiYXVkIjoiY29tLnB1c2hkZWVyLnNlbGYuaW9zIiwiZXhwIjoxNjQ2NDYyNTQyLCJpYXQiOjE2NDYzNzYxNDIsInN1YiI6IjAwMDI0MS41Mjc1Y2E4M2YwNzU0ZjY0YjMwNjc3NTNiZjZhOTE4Ni4wMTAxIiwiY19oYXNoIjoiWGNOUUtkc2NXakdaaWd6NzhfYXhjdyIsImVtYWlsIjoiMTM5MDczMTc4NjdAMTM5LmNvbSIsImVtYWlsX3ZlcmlmaWVkIjoidHJ1ZSIsImF1dGhfdGltZSI6MTY0NjM3NjE0Miwibm9uY2Vfc3VwcG9ydGVkIjp0cnVlfQ.IiCauTcSPsqa-2a72UaT1dDulXVIKs9tiyMEDvnzNWlM1cKbBilQ4ASNUezc6bmgdd_dnzrTuKLvnrg" 404 /app/api/public/index.php 26.098 4096 76.63%
pushdeer-app-1      | docker.vm:80 172.28.144.1 - - [04/Mar/2022:14:56:08 +0800] "GET /favicon.ico HTTP/1.1" 200 259 "http://222.247.54.30:43826//login/idtoken?idToken=eyJraWQiOiJZdXlYb1kiLCJhbGciOiJSUzI1NiJ9.eyJpc3MiOiJodHRwczovL2FwcGxlaWQuYXBwbGUuY29tIiwiYXVkIjoiY29tLnB1c2hkZWVyLnNlbGYuaW9zIiwiZXhwIjoxNjQ2NDYyNTQyLCJpYXQiOjE2NDYzNzYxNDIsInN1YiI6IjAwMDI0MS41Mjc1Y2E4M2YwNzU0ZjY0YjMwNjc3NTNiZjZhOTE4Ni4wMTAxIiwiY19oYXNoIjoiWGNOUUtkc2NXakdaaWd6NzhfYXhjdyIsImVtYWlsIjoiMTM5MDczMTc4NjdAMTM5LmNvbSIsImVtYWlsX3ZlcmlmaWVkIjoidHJ1ZSIsImF1dGhfdGltZSI6MTY0NjM3NjE0Miwibm9uY2Vfc3VwcG9ydGVkIjp0cnVlfQ.IiCauTcSPsqa-2a72UaT1dDulXVIKs9tiyMEDvnzNWlM1cKbBilQ4ASNUezc6bmgdd_dnzrTuKLvnrgNvQ5_lz4U-mCatdNY9dC75zgUj0VpTGb2CVoPgQlpV5gGoD6kQGMKLjKZblH67q1klmp3qdOccc3E8TQPt9qwRAtHSXidkYsTb82l85jFsF5sCBl8pzNzB_IGrhfGkOQgY28vwlFiMHKx1Ps04-LF6I0lGs8Ik-oK-KKugDIZy2sjYcQE76Tfrbaypz8jet5mKbdfbW_rsij_GhzCk8QFBoQpeCyCKjqs1jseVWBeb9ohIJSONNUcnADuwLfjLlGgNAP3WA" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/98.0.4758.102 Safari/537.36"
pushdeer-app-1      | [httpd:access] 222.247.54.30:80 - - 172.28.144.1 - - [04/Mar/2022:14:56:08 +0800] "GET /favicon.ico HTTP/1.1" 200 bytesIn:1602 bytesOut:259 reqTime:0

**Comment by easychen** [comment]
https://blog.51cto.com/u_10698621/3646204

**Comment by wuquejs** [comment]
<img width="1250" alt="Image" src="https://github.com/user-attachments/assets/ac62fec6-4039-4cd6-96ba-e58839ac52a3" />

我遇到了同样的内容，这个是我使用apifox请求后的结果
