### ISSUE TITLE
[建议] iOS 应用内打开网页建议使用 BetterSafariView

### ISSUE THREAD

**Issue by LouisTay** [easychen/pushdeer#91]
现在用的这个 `struct SafariView: UIViewControllerRepresentable` 在 SwiftUI 里显示出来效果并不好，在刘海屏 iPhone 上下都未占满。SwiftUI 开源方案里里封装的比较好的一个就是 [BetterSafariView](https://github.com/stleamist/BetterSafariView)。具体可以看看里面的效果图，和直接用 UIKit 的效果几乎一样。

用了这个之后 View 里面的代码也没多少需要改动的。

**Comment by easychen** [comment]
感谢反馈，iOS1.5已经换上了。
