### ISSUE TITLE
[Bug]IOS14.4下，App Store上自架客户端存在消息列表滑动时存在UI冻结的现象

### ISSUE THREAD

**Issue by lishangbu** [easychen/pushdeer#95]
**描述你遇到的Bug**

向下滑动时，滑动大约20条消息后UI就会卡死

以下内容不是必填，但越详细越能帮助我们解决问题。

**重现**

重现步骤:

1. 将应用后台杀掉，打开应用
2. 点击消息页签，向下划动消息之后再尝试向上滑动，在快到消息头时整个UI会彻底卡死
3. 此时，不管是消息，设置，设备，key等任何一个页签都无法点击
4. 将消息界面的推送测试界面收缩后，使全屏幕都是消息列表时错误复现率更高

**期望的结果**

**截图**

**自架服务器端请填写以下信息**

按 [调试文档](/doc/调试文档.md) 进行调试的结果：

**API服务启动输出截图**

**联通性测试截图**

**命令行推送返回截图**

**客户端请填写以下信息**

**环境和版本**
 - 系统: iOS14
 - 版本： 
 - 模块：APP Store上的自架客户端 
 - 版本号 1.4

**手机或电脑的的详细信息**
 - Device: iPhone13
 - OS: iOS14.4.2
 
**其他说明**
总计约50条消息

**Comment by Hext123** [comment]
你的消息格式可以给一个示例吗? 

目前发现markdown中相对路径的图片或url可能引发次问题

如果是的, 可以暂时避免使用相对路径, 改为绝对路径

**Comment by easychen** [comment]
已经优化了一个版本，试试iOS1.5

**Comment by lishangbu** [comment]
> 你的消息格式可以给一个示例吗?
> 
> 目前发现markdown中相对路径的图片或url可能引发次问题
> 
> 如果是的, 可以暂时避免使用相对路径, 改为绝对路径

就是普通文本消息，消息中除了文案以后就几个符号:```:```,```[```,```]```,```(```,```)```,其他的都是中文，英文跟数字而已

**Comment by lishangbu** [comment]
> 已经优化了一个版本，试试iOS1.5

试了下没有改善，我尝试看看有没有录屏吧

**Comment by lishangbu** [comment]
你们是不是在APP内缓存消息了?
请看以下视频中的内容，基本上上下滚动之后就不能操作了，20s之后不是我没操作，而是根本动不了

https://user-images.githubusercontent.com/36465346/161432169-b9eaa05c-2409-47e1-baf8-af0cb2b8160a.mp4
