### ISSUE TITLE
请问怎么避免 429 TOO MANY REQUESTS？

### ISSUE THREAD

**Issue by SouSuoKe** [easychen/pushdeer#96]
我需要给多个人多个key推送消息，现在访问 https://api2.pushdeer.com/message/push 已经提示 429TOO MANY REQUESTS，请问每分钟最多能发多少条？

**Comment by easychen** [comment]
在线版一分钟60次请求。自架版可以通过 MAX_PUSH_EVERY_USER_PER_MINUTE 环境变量进行调整。

**Comment by SouSuoKe** [comment]
> 在线版一分钟60次请求，多个key可以通过英文逗号隔开（一次最多10个）。自架版可以通过 MAX_PUSH_EVERY_USER_PER_MINUTE 环境变量进行调整。

请问我现在需要做什么才能恢复正常访问？
